# Autogenerated wrapper script for z5_jll for any
export z5

using Blosc_jll
using Bzip2_jll
using Lz4_jll
using XZ_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("z5")
JLLWrappers.@declare_file_product(z5)
function __init__()
    JLLWrappers.@generate_init_header(Blosc_jll, Bzip2_jll, Lz4_jll, XZ_jll, Zlib_jll)
    JLLWrappers.@init_file_product(
        z5,
        "include/z5/z5.hxx",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
